# Generated by Django 3.2.7 on 2021-09-03 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import micro_tasks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=13)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='micro_tasks.user')),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed', models.BooleanField(default=False, verbose_name='Performer')),
                ('initiator', models.BooleanField(default=False, verbose_name=micro_tasks.models.Initaitor)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro_tasks.user')),
            ],
        ),
        migrations.CreateModel(
            name='Initaitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initiated', models.PositiveSmallIntegerField(choices=[(0, 'Facebook'), (1, 'YouTube'), (2, 'Twitter'), (3, 'Instagram'), (4, 'TikTok'), (5, 'Snapchat')], verbose_name='Initiated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='micro_tasks.user')),
            ],
        ),
    ]
