# Generated by Django 3.2.7 on 2021-09-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initaitor',
            name='num_of_followers_req',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='initaitor',
            name='initiated',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Facebook'), (1, 'YouTube'), (2, 'Twitter'), (3, 'Instagram'), (4, 'TikTok'), (5, 'Snapchat')], default=3, verbose_name='Initiated'),
        ),
    ]
