# Generated by Django 3.2.7 on 2021-09-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('micro_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Facebook'), (1, 'YouTube'), (2, 'Twitter'), (3, 'Instagram'), (4, 'TikTok'), (5, 'Snapchat')], default=3, max_length=15),
        ),
    ]
